version: '2'

services:
  wordpress:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./wp:/var/www/html
      - ./srdb:/srdb
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: sysart_wp

  mysql:
    image: mariadb
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
