<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_582309558423f',
	'title' => 'Blog page',
	'fields' => array (
		array (
			'key' => 'field_57c5141bf4bc0',
			'label' => 'blogs',
			'name' => 'blogs',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'blog',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_57c51442f4bc1',
			'label' => 'filter buttons',
			'name' => 'filter',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_tag',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'load_save_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
			'add_term' => 1,
			'load_terms' => 0,
			'save_terms' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-blog.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 456,
));

acf_add_local_field_group(array (
	'key' => 'group_5823095592c8d',
	'title' => 'Blog post',
	'fields' => array (
		array (
			'key' => 'field_57c514ae61f21',
			'label' => 'description',
			'name' => 'description',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57c514b961f22',
			'label' => 'jumbotron text',
			'name' => 'jumbotron_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57c514c561f23',
			'label' => 'jumbotron image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_57c514d861f24',
			'label' => 'content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 1,
			'tabs' => 'all',
		),
		array (
			'key' => 'field_57c514ef61f25',
			'label' => 'author',
			'name' => 'author',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'employee',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_57c5150c61f26',
			'label' => 'related articles',
			'name' => 'related_articles',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'blog',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_57cc5fb6e2434',
			'label' => 'share text',
			'name' => 'share_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_57cc5fcae2435',
			'label' => 'share image',
			'name' => 'share_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_57cc5ff1e2436',
			'label' => 'share title',
			'name' => 'share_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57ce87aa1e457',
			'label' => 'twitter text',
			'name' => 'twitter_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57ce87b11e458',
			'label' => 'twitter tags',
			'name' => 'twitter_tags',
			'type' => 'text',
			'instructions' => 'comma separated list
kissa, koira, jorma',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'blog',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 457,
));

acf_add_local_field_group(array (
	'key' => 'group_58230955c2898',
	'title' => 'clients',
	'fields' => array (
		array (
			'key' => 'field_5773e4538b208',
			'label' => 'image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5773e4618b209',
			'label' => 'description',
			'name' => 'description',
			'type' => 'textarea',
			'instructions' => 'short text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_5773e4778b20a',
			'label' => 'text',
			'name' => 'text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 0,
			'tabs' => 'all',
		),
		array (
			'key' => 'field_5773e4858b20b',
			'label' => 'employees',
			'name' => 'employees',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'employee',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_5777779f35ff9',
			'label' => 'full preview',
			'name' => 'full_preview',
			'type' => 'true_false',
			'instructions' => 'Preview etusivulla feat texti',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_577a97de966e9',
			'label' => 'footer preview',
			'name' => 'footer_preview',
			'type' => 'true_false',
			'instructions' => 'näytä asiakkaat sivun alareunassa "muita asiakkaitamme" -osiossa.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_57a0fad634fb8',
			'label' => 'key numbers',
			'name' => 'key_numbers',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'object',
			'post_type' => array (
				0 => 'keynumbers',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_57adacfe3b38b',
			'label' => 'share title',
			'name' => 'share_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57adad063b38c',
			'label' => 'share text',
			'name' => 'share_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57adad123b38d',
			'label' => 'share image',
			'name' => 'share_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_57adb3cc3f0bf',
			'label' => 'twitter text',
			'name' => 'twitter_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57adb3d53f0c0',
			'label' => 'twitter tags',
			'name' => 'twitter_tags',
			'type' => 'text',
			'instructions' => 'COMMA SEPARATED LIST WITHOUT # IN THEM
like as if yolo,swag,kissa,koira',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57c516a1f7de2',
			'label' => 'related articles',
			'name' => 'related',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'blog',
				1 => 'article',
				2 => 'news',
				3 => 'client',
				4 => 'service',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_58120bb61e22b',
			'label' => 'Disable Link to client page',
			'name' => 'disable_link',
			'type' => 'true_false',
			'instructions' => 'Estää kuvan linkittymisen asiakkaan sivulle. Esimerkiksi "Tulossa Pian!" -asiakkaissa joita ei haluta linkittyvän.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'client',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 15,
));

acf_add_local_field_group(array (
	'key' => 'group_5823095602fd1',
	'title' => 'contact infos',
	'fields' => array (
		array (
			'key' => 'field_578b4ad60e411',
			'label' => 'subtitle',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => 'Another title, used in different occasions',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_578b55fdf35b6',
			'label' => 'image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'contactinfo',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 85,
));

acf_add_local_field_group(array (
	'key' => 'group_582309560dcaf',
	'title' => 'Contact page',
	'fields' => array (
		array (
			'key' => 'field_5800c5d249882',
			'label' => 'Pipedrive form ID',
			'name' => 'pipedrive_form_id',
			'type' => 'text',
			'instructions' => 'Pipedrive lomakkeen ID. Lomakkeen luonnin yhteydessä tulevasta urlista, ID osuus esim. "https://pipedrivewebforms.com/form/127dbe1fb535cf55782b22fc6617ac5d" ID on "127dbe1fb535cf55782b22fc6617ac5d"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '63',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 655,
));

acf_add_local_field_group(array (
	'key' => 'group_582309561b018',
	'title' => 'contact people',
	'fields' => array (
		array (
			'key' => 'field_578bb094ae74d',
			'label' => 'employees',
			'name' => 'employees',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'object',
			'post_type' => array (
				0 => 'employee',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '63',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 94,
));

acf_add_local_field_group(array (
	'key' => 'group_5823095623696',
	'title' => 'employees',
	'fields' => array (
		array (
			'key' => 'field_5773e654df8d6',
			'label' => 'image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5773e61edf8d2',
			'label' => 'title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5773e629df8d3',
			'label' => 'phone',
			'name' => 'phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5773e637df8d4',
			'label' => 'email',
			'name' => 'email',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '@sysart.fi',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5773e646df8d5',
			'label' => 'description',
			'name' => 'description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_5773e665df8d7',
			'label' => 'text',
			'name' => 'text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 1,
			'tabs' => 'all',
		),
		array (
			'key' => 'field_57dd858412c3f',
			'label' => 'linkedin profile link',
			'name' => 'link_linkedin',
			'type' => 'text',
			'instructions' => 'linkedin link',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57dd859812c40',
			'label' => 'twitter profile link',
			'name' => 'link_twitter',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57dd85c512c41',
			'label' => 'github profile link',
			'name' => 'link_github',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57dd85d512c42',
			'label' => 'homepage link',
			'name' => 'link_homepage',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'employee',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 21,
));

acf_add_local_field_group(array (
	'key' => 'group_582310d2298b0',
	'title' => 'Jobs page',
	'fields' => array (
		array (
			'key' => 'field_582310ec171f6',
			'label' => 'Benefits',
			'name' => 'benefits',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 6,
			'max' => 6,
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_58231128171f7',
					'label' => 'Benefit',
					'name' => 'benefit',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58231136171f8',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_58231173171f9',
			'label' => 'Jobs title',
			'name' => 'jobs_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Tarjolla olevat duunit:',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-jobs.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_582309564e3c5',
	'title' => 'MainPage',
	'fields' => array (
		array (
			'key' => 'field_57775a56a0933',
			'label' => 'logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => 'top menu logo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5773fcaeb3092',
			'label' => 'jumbotron image',
			'name' => 'jumbotron_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5773fca0b3091',
			'label' => 'jumbotron text',
			'name' => 'jumbotron_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57dd851774713',
			'label' => 'jumbotron excerpt',
			'name' => 'jumbotron_excerpt',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_577773bbc0971',
			'label' => 'jumbotron link',
			'name' => 'jumbotron_link',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'taxonomy' => array (
			),
			'allow_archives' => 1,
		),
		array (
			'key' => 'field_5773e38d07c4c',
			'label' => 'main title',
			'name' => 'main_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5773e3ab07c4d',
			'label' => 'image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5768e900863c3',
			'label' => 'services',
			'name' => 'services',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'service',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_57cd44e0dd40c',
			'label' => 'hilights',
			'name' => 'hilights',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'post',
				1 => 'page',
				2 => 'blog',
				3 => 'article',
				4 => 'employee',
				5 => 'news',
				6 => 'client',
				7 => 'service',
				8 => 'jobs',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_5768e885863c2',
			'label' => 'Clients',
			'name' => 'clients',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'client',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_5773e3fa07c4e',
			'label' => 'share title',
			'name' => 'share_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5773e40507c4f',
			'label' => 'share image',
			'name' => 'share_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5773e41307c50',
			'label' => 'share text',
			'name' => 'share_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57776dfa4838e',
			'label' => 'footer',
			'name' => 'footer',
			'type' => 'textarea',
			'instructions' => 'Taika-input jossa paljon taikoja
räjähtää ihan varmasti jos sössit',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Helsinki
Itämerenkatu 5
00180 Helsinki
040 123 1234

Oulu
Yrittipellontie 1D
90230 Oulu
040 123 1234

ASIAKASPALVELU SOPIMUSASIAKKAILLE
+358 40 502 0671
helpdesk@sysart.fi',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 20,
			'new_lines' => '',
		),
		array (
			'key' => 'field_57776e894838f',
			'label' => 'footer image',
			'name' => 'footer_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_57c95a2f9ae61',
			'label' => 'meta description',
			'name' => 'meta_description',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
		),
		array (
			'key' => 'field_57c95a3e9ae62',
			'label' => 'meta keywords',
			'name' => 'meta_keywords',
			'type' => 'text',
			'instructions' => 'comma separated list as kissa, koira, kala, jorma',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-main.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'author',
		6 => 'format',
		7 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 5,
));

acf_add_local_field_group(array (
	'key' => 'group_582309568b25d',
	'title' => 'processes',
	'fields' => array (
		array (
			'key' => 'field_57a0f9c6ffd1b',
			'label' => 'image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'processes',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 266,
));

acf_add_local_field_group(array (
	'key' => 'group_582309569264f',
	'title' => 'service',
	'fields' => array (
		array (
			'key' => 'field_5773e5024ef3b',
			'label' => 'icon',
			'name' => 'icon',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5773e4f24ef3a',
			'label' => 'description',
			'name' => 'description',
			'type' => 'textarea',
			'instructions' => 'short text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array (
			'key' => 'field_5773e52a4ef3d',
			'label' => 'image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'return_format' => 'array',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5773e50e4ef3c',
			'label' => 'text',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 0,
			'tabs' => 'all',
		),
		array (
			'key' => 'field_57a0f990488f1',
			'label' => 'processes',
			'name' => 'processes',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'object',
			'post_type' => array (
				0 => 'processes',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'service',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 16,
));

acf_add_local_field_group(array (
	'key' => 'group_58230956a5a36',
	'title' => 'Services page',
	'fields' => array (
		array (
			'key' => 'field_57778197534bf',
			'label' => 'services',
			'name' => 'services',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'post_type' => array (
				0 => 'service',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'max' => '',
			'min' => 0,
			'elements' => array (
				0 => 'post_type',
			),
		),
		array (
			'key' => 'field_5800c620ae07f',
			'label' => 'Pipedrive form ID',
			'name' => 'pipedrive_form_id',
			'type' => 'text',
			'instructions' => 'Pipedrive lomakkeen ID. Lomakkeen luonnin yhteydessä tulevasta urlista, ID osuus esim. "https://pipedrivewebforms.com/form/127dbe1fb535cf55782b22fc6617ac5d" ID on "127dbe1fb535cf55782b22fc6617ac5d"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-services.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'active' => 1,
	'description' => '',
	'old_ID' => 73,
));

endif;
